volumes:
  mssql_data:

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=sa@2025*
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    restart: always
    volumes:
      - mssql_data:/var/opt/mssql
  sqlserver.configurator:
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      - sqlserver

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq_container
    ports:
      - 15672:15672
      - 5672:5672
    restart: always
    hostname: "rabbitmq"
    environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
        RABBITMQ_DEFAULT_VHOST: "/"


